### ISSUE TITLE
It's not Owin.WebSocket, it's  System.Net.WebSockets.WebSocket

### ISSUE THREAD

**Issue by kekekeks** [Avanade/Owin.WebSocket#3]
Your library does not use http://owin.org/spec/extensions/owin-WebSocket-Extension-v0.4.0.htm specification, therefore can not be used on generic OWIN servers (NOwin, Kestrel, etc), only on HttpListener/IIS. 

Please, don't lie to users of your library and fix that.

**Comment by kekekeks** [comment]
See correct usage of specification [here](https://github.com/SignalR/SignalR/blob/8b7c92faf050a621abfd7dcfbe5fcdbe0a1c643a/src/Microsoft.AspNet.SignalR.Core/Owin/OwinWebSocketHandler.cs).

**Comment by bryceg** [comment]
Commited support for the spec
