### ISSUE TITLE
Unable to connect via browser websocket using windows 7

### ISSUE THREAD

**Issue by delaneyj** [Avanade/Owin.WebSocket#4]
Using chrome created a [direct copy](https://msdn.microsoft.com/en-us/library/ie/hh673567(v=vs.85).aspx) of of the reference to websockets found in the documention.

index.html
```html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <div>
        ServerStatus
        <div id="serverStatus"></div>
        Destination
        <div id="destination"></div>
        Server Response
        <div id="serverResponse"></div>
        TextMessage
        <div id="textmessage"></div>
        Source
        <div id="source"></div>
    </div>
    <script>
        try {
            socket = new WebSocket("ws://localhost:1337/ws");

            socket.onopen = function (openEvent) {
                document.getElementById("serverStatus").innerHTML = 
                   'WebSocket Status:: Socket Open';
            };

            socket.onmessage = function (messageEvent) {

                if (messageEvent.data instanceof Blob) {
                    var destinationCanvas = document.getElementById('destination');
                    var destinationContext = destinationCanvas.getContext('2d');
                    var image = new Image();
                    image.onload = function () {
                        destinationContext.clearRect(0, 0, 
                           destinationCanvas.width, destinationCanvas.height);
                        destinationContext.drawImage(image, 0, 0);
                    }
                    image.src = URL.createObjectURL(messageEvent.data);
                } else {
                    document.getElementById("serverResponse").innerHTML = 
                       'Server Reply:: ' + messageEvent.data;
                }
            };

            socket.onerror = function (errorEvent) {
                document.getElementById("serverStatus").innerHTML = 
                  'WebSocket Status:: Error was reported';
            };

            socket.onclose = function (closeEvent) {
                document.getElementById("serverStatus").innerHTML = 
                  'WebSocket Status:: Socket Closed';
            };
        }
        catch (exception) { if (window.console) console.log(exception); }
        
        function sendTextMessage() {

            if (socket.readyState != WebSocket.OPEN) return;

            var e = document.getElementById("textmessage");
            socket.send(e.value);
        }

        function sendBinaryMessage() {
            if (socket.readyState != WebSocket.OPEN) return;

            var sourceCanvas = document.getElementById('source');

            socket.send(sourceCanvas.msToBlob());
        }    

    </script>
</body>
</html>
```

Then used the following to try to bootstrap up a test.

Program.cs
```C#
using System;
using System.Diagnostics;
using System.Net.WebSockets;
using System.Threading.Tasks;
using Microsoft.Owin.FileSystems;
using Microsoft.Owin.Hosting;
using Microsoft.Owin.StaticFiles;
using Owin;
using Owin.WebSocket;
using Owin.WebSocket.Extensions;

namespace WebsocketServer
{
    class Program
    {
        const int port = 1337;
        private static readonly string url = "http://localhost:\{port}";

        static void Main(string[] args)
        {
            using (WebApp.Start<Startup>(url))
            {
                //StartChrome();

                Console.WriteLine("Running on \{url}");
                Console.WriteLine("Press enter to exit");
                Console.ReadLine();
            }
        }
    }

    class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.MapWebSocketRoute<MyWebSocket>("/ws");
            app.UseFileServer(new FileServerOptions()
            {
                EnableDirectoryBrowsing = true,
                FileSystem = new PhysicalFileSystem("../..")
            });
        }
    }

    public class MyWebSocket : WebSocketConnection
    {
        public override Task OnMessageReceived(ArraySegment<byte> message, WebSocketMessageType type)
        {
            //Handle the message from the client
            //Example of JSON serialization with the client
            //    //var json = Encoding.UT8.GetString(message.Array, message.Offset, message.Count);
            //    //Use something like Json.Net to read the json
            Debugger.Break();
            return null;
        }

        public override void OnOpen()
        {
            Debugger.Break();
            SendText(new byte[] { }, true);
        }

        //public override void OnClose(WebSocketCloseStatus closeStatus, string closeDescription){}
        //public override bool Authenticate(IOwinContext requestContext){return true;}
    }
}
```

Chrome & IE consoles are both saying ```WebSocket connection to 'ws://localhost:1337/ws' failed: Error during WebSocket handshake: Unexpected response code: 400```.  Are there handshakes that aren't being completed properly?

**Comment by bryceg** [comment]
It looks like you are using c# 6?  I just tried your code on .net 4.5 (had to remove string interpolation) and this all worked as expected.  Do you have a solution you can provide and I'll try it out to repro?

**Comment by delaneyj** [comment]
I am using C# 6, very curious what would have changed to cause this issues.  https://drive.google.com/file/d/0ByqZxd4iFhIUZVhJTlVKZkdxLVU/view?usp=sharing  here is an isolated solution, let me know if there is anything else I can do.

**Comment by bryceg** [comment]
Using the latest VS CTP 5 release from MS I got this working.  It appears your using an older version which may be your issue, as they changed string interopolation in the latest release which tipped me off to the potential issue with an older version:

```
const int port = 1337;
private static readonly string url = $"http://localhost:{port}";
```

I can give you access to my Azure VM I tested this on if you want to try it yourself.

**Comment by delaneyj** [comment]
Upgraded to CTP5, changed the string interpolation, set the target framework to 4.6 and relaunched... Exact same error on my side ```Error during WebSocket handshake: Unexpected response code: 400```,

[Here is my new project](https://drive.google.com/open?id=0ByqZxd4iFhIUTl9PWUhWbHQwa3M&authuser=0)  Not sure what to do.  Are you using the project's web page with the js websocket?

**Comment by bryceg** [comment]
I have an azure test vm I tried this on, why don't you RDP into it and see if that project I tested with is different from yours in some way.  owin-test.cloudapp.net  bryceg:WebSocket!

**Comment by delaneyj** [comment]
Yeah it seems to work there, now I have no idea what to think.  Change the ports to a few others just to make sure locally.  I'll try on another machine, this is a windows 7 pro x64 box.

**Comment by delaneyj** [comment]
Okay at work it opens properly.. but that's a windows 8 box.  Is your azure vm windows 8 as well?  Anything windows 8 specific in your implementation?

**Comment by bryceg** [comment]
The VM is server 2012 r2.  There is nothing specific in my code for OS, you can try forking and running against the source to see whats going on with Win7 if you would like.  The only time my code returns a 400 is when trying to accept the websocket through OWIN which you can see on line 157 here https://github.com/Avanade/Owin.WebSocket/blob/master/src/Owin.WebSocket/WebSocketConnection.cs

OWIN is doing the handshake work under the hood though as outlined in their spec (http://owin.org/spec/extensions/owin-WebSocket-Extension-v0.4.0.htm), so if that's not happening it's probably down in their code.

**Comment by delaneyj** [comment]
http://stackoverflow.com/questions/12073455/net-4-5-websocket-server-running-on-windows-7

Looks like its not supported by the underlying frameworks you are building on.  Unless you decide to use an independent library (super/fleck/alchemy) its probably a good idea to mark this as a windows 8/r12 owin lib for now and close this issue.  Otherwise I'm glad to help with whatever testing I can supply.

**Comment by bryceg** [comment]
Thanks for digging that up, I'll just add a note about the OS support on the front of the project page.
